# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Another Fine Way"

# Site logo
logo:

# A description of your site for social meta tag, search engines, and feed.xml
description: "Travel, work and life, one country at a time."

# Tagline below the site title
tagline: "To stay in one place is a fine way. But this is another one."

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://justgoodthemes.com"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Style Guide
  url: /style-guide/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus: another-fine-way

# Author information - author info at the bottom of the post
author_name: "Chris"
author_bio: "For years I dreamed of quitting my job, travelling the world, and creating my own business. Then I did. This is my story."
author_url: "http://anotherfineway.com"
#author_location: "Vilnius, Lithuania"
#author_image: authorimage.jpg

# Footer ad banner
banner_url: "https://myspiffysite.com/"
banner_image: banner.jpg

# Footer newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "https://gmail.us5.list-manage.com/subscribe/post?u=da0681326531ea4295e6cb885&amp;id=c4463606d7"

# Social links in the site footer
#twitter_username: "username"
#facebook_username: "username"
#googleplus_username: "+username"
#github_username: "username"
#codepen_username: "username"
#dribbble_username: "username"
#medium_username: "@username"
instagram_username: "malaclypse2323"
#pinterest_username: "username"
#linkedin_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
