# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "On the Road"

# Site logo
logo:

# A description of your site for social meta tag, search engines, and feed.xml
description: "BlogBox is a bold theme for the Jekyll blogging platform. Available for purchase at ThemeForest.net."

# Tagline below the site title
tagline: "Tales of a digital nomad."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://justgoodthemes.com"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Style Guide
  url: /style-guide/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus: justgoodthemes

# Author information - author info at the bottom of the post
author_name: "Chris Erickson"
author_bio: "My name is John Doe. I’m a full-time adventure travel blogger and photographer who’s been exploring the world for over 6 years."
author_url: "https://ericksonc.github.io"
#author_location: "Vilnius, Lithuania"
#author_image: authorimage.jpg

# Footer ad banner
banner_url: "https://justgoodthemes.com/"
banner_image: banner.jpg

# Footer newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "https://gmail.us5.list-manage.com/subscribe/post?u=da0681326531ea4295e6cb885&amp;id=c4463606d7"

# Social links in the site footer
#twitter_username: "username"
#facebook_username: "username"
#googleplus_username: "+username"
#github_username: "username"
#codepen_username: "username"
#dribbble_username: "username"
#medium_username: "@username"
instagram_username: "Chris0522"
#pinterest_username: "username"
#linkedin_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
